### ISSUE TITLE
Repository is being littered with useless commits

### ISSUE THREAD

**Issue by thias** [51Degrees/device-detection-nginx#143]
Checking if we were running the latest version of the module, I saw that there is currently about one new release per day! But those are triggered by some automation, and there seems to be a bug since most of the time there are no real changes, only line ordering differences in the tests. For instance: https://github.com/51Degrees/device-detection-nginx/commit/1cd91cc1f361566bfeefa07a9beb7d4629461fae

**Comment by Sara51D** [comment]
Hi @thias ,  Thank you for raising this, we are looking into it and will update you as soon as we have more information.

**Comment by Sara51D** [comment]
Hi @thias , The issue was due to a CI script tossing the lines of an options.json file because it was generated from an unordered hash - we now changed the hash to ordered so generated file now does not change without purpose and no longer causes commits.  You might still see Submodule Update commits or Package Update commits that propagate changes from dependencies, but no useless commits any more.  Thank you for bringing our attention to this issue!
